server:
  port: "8080"
  readTimeout: 10
  writeTimeout: 10

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "123456"
  dbname: "trivia_db"
  sslmode: "disable"

redis:
  # Режим работы: "single" (по умолчанию), "sentinel", "cluster"
  mode: "single"
  # Список адресов (хост:порт). Обязательно для sentinel и cluster.
  # Для single используется, если указан. Иначе используется addr.
  addrs: ["localhost:6379"]
  # Альтернативный адрес для single mode (если addrs пуст)
  addr: "localhost:6379"
  password: ""
  db: 0
  # Имя master-сервера (только для sentinel mode)
  master_name: ""
  # Параметры переподключения (опционально)
  # max_retries: 3
  # min_retry_backoff: 8 # ms
  # max_retry_backoff: 512 # ms

# --- Примеры других конфигураций Redis --- #
# sentinel:
#   mode: "sentinel"
#   addrs: ["host1:26379", "host2:26379", "host3:26379"]
#   password: "sentinel_password"
#   master_name: "mymaster"
#   db: 0
# cluster:
#   mode: "cluster"
#   addrs: ["host1:7000", "host2:7001", "host3:7002"]
#   password: "cluster_password"

jwt:
  secret: "your_super_secret_key_change_in_production"
  expirationHrs: 24
  wsTicketExpirySec: 60 # Время жизни WS тикета в секундах (1 минута)
  cleanup_interval: "1h" # Интервал очистки кеша инвалидированных токенов (например, 1h, 30m)

auth:
  sessionLimit: 10  # Максимальное количество активных сессий на пользователя
  refreshTokenLifetime: 720  # Время жизни refresh-токена в часах (30 дней)

# Настройки WebSocket подсистемы
websocket:
  # Настройки шардирования
  sharding:
    enabled: true
    shardCount: 4                   # Количество шардов
    maxClientsPerShard: 5000        # Максимальное количество клиентов на шард

  # Настройки буферов и производительности
  buffers:
    clientSendBuffer: 64            # Размер буфера сообщений для клиента
    broadcastBuffer: 128            # Размер буфера для широковещательных сообщений
    registerBuffer: 64              # Размер буфера для регистрации клиентов
    unregisterBuffer: 64            # Размер буфера для отмены регистрации клиентов
    
  # Настройки приоритизации сообщений
  priority:
    enabled: true
    highPriorityBuffer: 256         # Буфер для сообщений высокого приоритета
    normalPriorityBuffer: 128       # Буфер для сообщений обычного приоритета
    lowPriorityBuffer: 64           # Буфер для сообщений низкого приоритета
    
  # Настройки пингов для проверки соединения
  ping:
    interval: 30                    # Интервал между пингами в секундах
    timeout: 10                     # Тайм-аут ожидания понга в секундах
    
  # Настройки кластеризации для распределенного режима
  cluster:
    enabled: false                  # Включена ли кластеризация
    instanceID: ""                  # ID экземпляра (автогенерация, если пусто)
    broadcastChannel: "ws:broadcast" # Канал Redis для широковещательных сообщений
    directChannel: "ws:direct"      # Канал Redis для прямых сообщений
    metricsChannel: "ws:metrics"    # Канал Redis для обмена метриками
    metricsInterval: 60             # Интервал обновления метрик в секундах

  # Настройки для тайм-аутов и ограничений
  limits:
    maxMessageSize: 65536           # Максимальный размер сообщения в байтах (64KB)
    writeWait: 10                   # Тайм-аут записи в секундах
    pongWait: 60                    # Тайм-аут ожидания понга в секундах
    maxConnectionsPerIP: 100        # Макс. количество подключений с одного IP
    cleanupInterval: 300            # Интервал очистки неактивных клиентов в секундах